name: Runcoding - Learn to Code
url: https://runcoding.netlify.com/
markdown: kramdown
highlighter: rouge

collections:
  posts:
  cursos:
  videos:
  portafolios:

plugins:
  - jekyll-paginate
  - jekyll-gist
  
paginate: 5
paginate_path: "/blog/page:num/"
