name: Runcoding
url: https://runcoding.netlify.app/
markdown: kramdown
highlighter: rouge

collections:
  posts:
  cursos:

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-toc 
  - jekyll-codepen
  - jekyll-youtube
  
paginate: 9
paginate_path: "/blog/:num/"
