name: Runcoding - Learn to Code
url: https://runcoding.netlify.com/
markdown: kramdown
highlighter: rouge

collections:
  posts:
  cursos:
  portafolios:

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
