backend:
  name: github
  repo: ismaeldevmw/runcoding # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "/assets/img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    slug: "{{project_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "string",  required: true}
      - {label: "Thumbnail", name: "thumbnail",  widget: "image", required: true}
