backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: ismaeldevmw/runcoding # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/assets/images/uploads" # Media files will be stored in the repo under images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Articulos" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Tags", name: "tags", "string",  required: true}
      - {label: "Thumbnail", name: "thumbnail",  widget: "image", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:year/:month/:day/:title"}
  - name: "cursos" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Cursos Item" # Used in the UI
    folder: "_cursos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Price", name: "price", widget: "string"}   
      - {label: "Thumbnail", name: "thumbnail",  widget: "image", required: true}
      - {label: "Link", name: "link", widget: "string" }
