backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  repo: ismaeldevmw/runcoding # Path to your Github repository
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/assets/images/uploads" # Media files will be stored in the repo under images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["webdev"]}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Content Table", name: "toc", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "cursos" # Used in routes, e.g., /admin/collections/:slug/edit
    label: "Cursos" # Used in the UI
    folder: "_cursos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: "/:title"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail",  widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

